version: '3.8'

services:
  quantum-kv-node1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11001:11001"
      - "12001:12001"
    volumes:
      - ./data/node1:/app/data
    command: >
      ./quantum-kv
      -grpcAddr=0.0.0.0:11001
      -raddr=quantum-kv-node1:12001
      -id=node1
      /app/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100M"
    tty: false
    stdin_open: false
    restart: unless-stopped

  quantum-kv-node2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11002:11001"
      - "12002:12001"
    volumes:
      - ./data/node2:/app/data
    command: >
      ./quantum-kv
      -grpcAddr=0.0.0.0:11001
      -raddr=quantum-kv-node2:12001
      -join=quantum-kv-node1:11001
      -id=node2
      /app/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100M"
    tty: false
    stdin_open: false
    restart: unless-stopped

  quantum-kv-node3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11003:11001"
      - "12003:12001"
    volumes:
      - ./data/node3:/app/data
    command: >
      ./quantum-kv
      -grpcAddr=0.0.0.0:11001
      -raddr=quantum-kv-node3:12001
      -join=quantum-kv-node1:11001
      -id=node3
      /app/data
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100M"
    tty: false
    stdin_open: false
    restart: unless-stopped